### ISSUE TITLE
Not possible to mock entire module, only module`s methods

### ISSUE THREAD

**Issue by Ohar** [nyrkovalex/test.me.js#1]
I prepared [test repository](https://github.com/Ohar/test-test-me) to demonstrate issue.

**Comment by nyrkovalex** [comment]
It appears that you were passing mocks incorrectly.
You should've used same strings as you module-under-test uses when `require`s its dependencies

```
// you have
const moduleA = require('./module-a'),
      moduleB = require('./module-b'),
      moduleC = require('./module-c');

// so you would use
moduleForTest = testMe(
  './module-for-test',
  {
    './module-a': stubModuleA,
    './module-b': stubModuleB,
    './module-c': stubModuleC
   }
).module.exports;
```

See [pull request](https://github.com/Ohar/test-test-me/pull/1) for details and some tips.

Happy testing!

PS I should probably update the doc to be clearer on such things
